/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rvmm;

/**
 *
 * @author DayeE
 */
public enum MapMakerPropertyType {
    RVMM_PANE,
    RVMM_LABEL,
    
    APP_PATH_RAW_MAP_DATA,
    
    RVMM_MAP_PANE,
    RVMM_INSTRUCTION_PANE,
    RVMM_OUTER_PANE,

    RVMM_NAME_LABEL,
    RVMM_NAME_TEXT_FIELD,
    RVMM_ITEMS_TABLE_VIEW,
    RVMM_NEW_MAP_DATA_DESCRIPTION,
    RVMM_SUBREGION_COLUMN,
    RVMM_CAPITAL_COLUMN,
    RVMM_LEADER_COLUMN,
    RVMM_RESET_VIEWPORT_BUTTON,
    RVMM_FIT_TO_POLYGON_BUTTON,
    RVMM_RENAME_MAP_BUTTON,
    RVMM_ADD_IMAGE_BUTTON,
    RVMM_REMOVE_IMAGE_BUTTON,
    RVMM_SNAP_IMAGE_TOP_LEFT_BUTTON,
    RVMM_SNAP_IMAGE_BOTTOM_LEFT_BUTTON,
    RVMM_RANDOMIZE_MAP_COLOR_BUTTON,
    RVMM_CHANGE_MAP_DIMENSION_BUTTON,
    RVMM_TOGGLE_MAP_LABEL,
    RVMM_TOGGLE_MAP_CHECK_BOX,
    RVMM_MOVE_POLYGON_MODE_LABEL,
    RVMM_MOVE_POLYGON_MODE_CHECK_BOX,
    RVMM_CHANGE_POLYGON_SUBREGION_BUTTON,
    RVMM_CHANGE_BORDER_COLOR_LABEL,
    RVMM_CHANGE_BORDER_COLOR_PICKER,
    RVMM_CHANGE_BORDER_THICKNESS_LABEL,
    RVMM_CHANGE_BORDER_THICKNESS_SLIDER,
    RVMM_MOVE_UP_BUTTON,
    RVMM_MOVE_DOWN_BUTTON,
    RVMM_GRADIENT_LABEL,
    RVMM_GRADIENT_SLIDER,
    RVMM_FOCUS_ANGLE_LABEL,
    RVMM_FOCUS_ANGLE_SLIDER,
    RVMM_RADIUS_LABEL,
    RVMM_RADIUS_SLIDER,
    RVMM_CENTER_X_LABEL,
    RVMM_CENTER_X_SLIDER,
    RVMM_FOCUS_DISTENCE_LABEL,
    RVMM_FOCUS_DISTENCE_SLIDER,
    RVMM_CENTER_Y_LABEL,
    RVMM_CENTER_Y_SLIDER,
    RVMM_PROPORTIONAL_LABEL,
    RVMM_PROPORTIONAL_CHECK_BOX,
    RVMM_STOP_0_COLOR_LABEL,
    RVMM_STOP_0_COLOR_PICKER,
    RVMM_CYCLE_METHOD_LABEL,
    RVMM_CYCLE_METHOD_COMBO_BOX,
    RVMM_STOP_1_COLOR_LABEL,
    RVMM_STOP_1_COLOR_PICKER,
    
    RVMM_FOOLPROOF_SETTINGS,
    
    RVMM_CHANGE_MAP_NAME_TITLE_TEXT,
    RVMM_CHANGE_MAP_NAME_CONTENT_TEXT,
    
    RVMM_CHANGE_POLYGON_SELECT_SUBREGION_TITLE_TEXT,
    RVMM_CHANGE_POLYGON_SELECT_SUBREGION_CONTENT_TEXT,
    RVMM_CHANGE_POLYGON_TITLE_TEXT,
    RVMM_CHANGE_POLYGON_CONTENT_TEXT,
    
    // New Map Dialog property
    RVMM_NEW_MAP_DIALOG_DEFAULT_DATA_TEXT,
    RVMM_NEW_MAP_DIALOG_DEFAULT_PARENT_TEXT,
    RVMM_NEW_MAP_DIALOG_HEADER,
    RVMM_NEW_MAP_DIALOG_HEADER_TEXT,
    RVMM_NEW_MAP_DIALOG_REGION_NAME,
    RVMM_NEW_MAP_DIALOG_REGION_TEXT,
    RVMM_NEW_MAP_DIALOG_REGION_NAME_TEXT_FIELD,
    RVMM_NEW_MAP_DIALOG_CHOOSE_PARENT_BUTTON,
    RVMM_NEW_MAP_DIALOG_CHOOSE_DATA_BUTTON,
    RVMM_NEW_MAP_DIALOG_OK_BUTTON,
    
    RVMM_CHANGE_DIMENSION_DIALOG_HEADER,
    RVMM_CHANGE_DIMENSION_DIALOG_HEADER_TEXT,
    RVMM_CHANGE_DIMENSION_DIALOG_HEIGHT_TEXT,
    RVMM_CHANGE_DIMENSION_DIALOG_HEIGHT_TEXT_FIELD,
    RVMM_CHANGE_DIMENSION_DIALOG_WIDTH_TEXT,
    RVMM_CHANGE_DIMENSION_DIALOG_WIDTH_TEXT_FIELD,
    
    RVMM_SUBREGION_DIALOG_HEADER_TEXT,
    RVMM_SUBREGION_DIALOG_SUBREGION,
    RVMM_SUBREGION_DIALOG_CAPITAL,
    RVMM_SUBREGION_DIALOG_LEADER,
    RVMM_SUBREGION_DIALOG_FLAG,
    RVMM_SUBREGION_DIALOG_SUBREGION_TEXT,
    RVMM_SUBREGION_DIALOG_CAPITAL_TEXT,
    RVMM_SUBREGION_DIALOG_LEADER_TEXT,
    RVMM_SUBREGION_DIALOG_FLAG_TEXT,
    RVMM_SUBREGION_DIALOG_SUBREGION_TEXT_FIELD,
    RVMM_SUBREGION_DIALOG_CAPITAL_TEXT_FIELD,
    RVMM_SUBREGION_DIALOG_LEADER_TEXT_FIELD,
    RVMM_SUBREGION_DIALOG_FLAG_IMAGE,
    RVMM_SUBREGION_DIALOG_OK_BUTTON,
      
    CYCLE_METHOD_DEFAULT,
    CYCLE_METHOD_OPTIONS    
}
